### PR TITLE
feat(241): implemented custom folder moving logic with user-defined instructions

### LINKED ISSUE #241: feat: add instructions for custom folder moving logic
## Background

File Organizer 2000 is an AI-powered plugin for Obsidian that helps users keep their vault organized. When a user moves a note to the File Organizer Inbox Folder, it's automatically moved to the most appropriate folder in the user's vault based on an AI request.

## Current Functionality

- Folder determination is handled by a non-customizable prompt in the `ai-service` file, specifically the `guessRelevantFolder` function.
- The plugin sends all folder names in the user's Obsidian app to this endpoint: `web/app/api/(newai)/folders/route.ts`.

## Proposed Feature

Allow users to add custom instructions for better folder determination:

1. **New Setting**: Add a new setting in the plugin's experimental features list for custom folder moving logic.
2. **User Instructions**: Enable users to write a few lines of instructions, similar to the existing renaming instructions in the plugin settings.

## Implementation Notes

- **UI Update**: Update the plugin settings UI to include the new custom instructions field.
- **AI Request Modification**: Modify the AI request to incorporate these custom instructions when determining the appropriate folder.
- **Toggle Feature**: Ensure the feature is toggleable in the customization tab of the plugin settings.

## Additional Information

- I will provide you with an openAI key to run the server
- Instructions on how to self-host can be found on our github readme

## Setup Instructions for Developers

1. **Install Obsidian**: Ensure Obsidian is installed if not already available.
2. **Install Plugin**: Clone the project into your vault (see loom video).
3. **Plugin Settings**: In the plugin settings, navigate to the customization tab.
4. **Toggle Settings**: Disable all toggles except the first two in customization section of settings, : renaming + logs to minimize openAI costs.

## Additional Developer Notes

- **API Key**: I will provide an API key necessary for accessing the AI-powered features.
- **Dev Mode**: Instructions on how to run the plugin in development mode within Obsidian will be provided to facilitate testing and debugging.

Ensure thorough testing of this new feature to maintain the plugin's reliability and user experience.

You'll need to clone the project inside a vault you created (Dev in this example). In the "plugins" folder as seen below
Screenshot 2024-09-21 at 2 17 19 PM 2

Reach out for any questions

Here's a loom video with a quick walkthrough: https://www.loom.com/share/c9b4cb3decf14662bba0393d20953576

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
Fixes #241 
/claim #241 

### Summary
- Added support for custom folder determination instructions in the settings.
- Introduced a toggle and text area in the customization tab to enable and input custom folder instructions.
- Updated `getAIClassifiedFolder` to handle and pass custom instructions to `guessRelevantFolder`.
- Modified `guessRelevantFolder` to incorporate custom folder logic by appending custom instructions to the decision-making prompt.
- Enhanced the API's POST method to accept and process custom folder instructions accordingly.

### Demonstration without Custom Instructions

https://github.com/user-attachments/assets/191379f0-aaca-47ff-b935-3d6fab97c805

### Demonstration with Custom Instructions for Moving the File

https://github.com/user-attachments/assets/8cf41c93-d949-4003-af12-5e7957663f9e

### CODE REVIEW

**Comment by aexshafii** [comment]
@akhilender-bongirwar thanks. I think there's still one small detail to fix: 
https://www.loom.com/share/60577a8892bd402087f91fb031bec0de

**Comment by aexshafii** [comment]
@akhilender-bongirwar might have been an Obsidian bug. Seems to be working now. Just testing more. Seems the instructions are not always being followed correctly. I've tried those instructions and they are sometimes overlooked: 

Screenshot 2024-09-28 at 11 12 09 AM

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar thanks. I think there's still one small detail to fix: https://www.loom.com/share/60577a8892bd402087f91fb031bec0de

@aexshafii you are right I just encountered that bug. But I have fixed it now. Please check the below video.

https://github.com/user-attachments/assets/f833ee67-b927-4557-afc2-a41162d5e27e

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar might have been an Obsidian bug. Seems to be working now. Just testing more. Seems the instructions are not always being followed correctly. I've tried those instructions and they are sometimes overlooked:
> 
> sometimes i have numbers in my titles and the file doesn't go to my daily folder for example. It seems the hardcoded instructions are followed instead, at times. When the custom instructions should supersede them (i.e. given more importance).
> Screenshot 2024-09-28 at 11 12 09 AM


After last commit, 

https://github.com/user-attachments/assets/72de2cd7-ba2b-47b5-bcb2-ee07cb03ebc2


https://github.com/user-attachments/assets/003db46f-e733-4a9b-a773-0897e86a60a6

**Comment by aexshafii** [comment]
@akhilender-bongirwar Thanks for the changes. Looks good. Will test later today and get back to you 🙏

**Comment by aexshafii** [comment]
Screenshot 2024-09-28 at 4 55 25 PM

Seems to be working well. But I noticed you removed part of the prompt. Could you add it back?

**Comment by akhilender-bongirwar** [comment]
Sure, I'll do it right now

**Comment by aexshafii** [comment]
@akhilender-bongirwar thanks a lot. Just sent you the reward.  🙏

**Pull request merged**
